version: '3.8'

services:

#MYSQL database
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

#PHP Laravel API
  api:
    build:
      context: ./api
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

#Nuxt.js Client
  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
    networks:
      - app-network

#Nginx web server
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
      - client
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
